// constants.js
module.exports = {
    MSG_YOUR_CART_CONTAINS_BLOCKED_PRODUCTS_PLEASE_REMOVE_THEM_TO_PROCEED: "Your cart contains blocked products. Please remove them to proceed.",
    MSG_FAILED_TO_CREATE_RAZORPAY_ORDER: "Failed to create Razorpay order.",
    MSG_INTERNAL_SERVER_ERROR: "Internal server error",
    MSG_COUPON_IS_INVALID: "Coupon is invalid!",
    MSG_COUPON_IS_EXPIRED: "Coupon is Expired!",
    MSG_COUPON_IS_ALREADY_USED: "Coupon is already used!",
    MSG_CART_NOT_FOUND: "Cart not found",
    MSG_YOUR_CART_CONTAINS_BLOCKED_PRODUCTS_CATEGORY_PLEASE_REMOVE_THEM_TO_PROCEED: "Your cart contains blocked products/category. Please remove them to proceed.",
    MSG_INSUFFICIENT_BALANCE_TO_PROCESS_THE_TRANSACTION: "Insufficient balance to process the transaction.",
    MSG_PRODUCT_ALREADY_EXIST: "product already exist",
    MSG_ALL_DONE: "All done",
    MSG_PASSWORDS_DO_NOT_MATCH: "passwords do not match",
    MSG_USER_WITH_THIS_EMAIL_ALREADY_EXIST: "User with this email already exist",
    MSG_USER_NOT_FOUND: "User not found",
    MSG_USER_IS_BLOCKED_BY_ADMIN: "User is blocked by admin",
    MSG_INCORRECT_PASSWORD: "Incorrect password",
    MSG_LOGIN_FAILED_PLEASE_TRY_AGAIN_LATER: "Login failed , Please try again later",
    MSG_EMAIL_NOT_FOUND_IN_SESSION: "Email not found in session",
    MSG_OTP_RESENT_SUCCESSFULLY: "otp resent successfully",
    MSG_FAILED_TO_RESENT_OTP_PLEASE_TRY_AGAIN: "Failed to resent otp,Please try again",
    MSG_INTERNAL_SERVER_ERROR_PLEASE_TRY_AGAIN: "Internal server error,please try again",
    MSG_INVALID_OTP_PLEASE_TRY_AGAIN: "Invalid OTP , Please try again",
    MSG_AN_ERROR_OCCURED: "An error occured",
    MSG_PROFILE_NAME_SUCCESSFULLY_EDITED: "profile name successfully edited",
    MSG_PASSWORD_NOT_MATCH: "Password not match",
    MSG_EMAIL_NOT_MATCH: "Email not match",
    MSG_PASSWORD_CHANGED_SUCCESSFULLY: "Password changed successfully",
    MSG_PASSWORD_CHANGE_ERROR: "Password change error",
    MSG_SERVER_WHILE_CHANGING_PASSWORD: "Server while changing password",
    MSG_INCORRECT_USERNAME_OR_PASSWORD: "Incorrect username or password",
    MSG_CATEGORY_ADDED_SUCCESSFULLY: "Category added successfully",
    MSG_INTERNAL_SERVER_ERROR_HAI: "Internal server error....HAI",
    MSG_OFFER_ADDED_SUCCESSFULLY: "Offer added successfully",
    MSG_FAILED_TO_ADD_OFFER: "Failed to add offer",
    MSG_OFFER_IS_REMOVED_SUCCESSFULLY: "Offer is removed Successfully",
    MSG_ERROR_IN_REMOVING_OFFER: "Error in removing offer",
    MSG_CATEGORY_NOT_FOUND: "Category not found",
    MSG_EDIT_SUCCESSFULL: "Edit successfull",
    MSG_FAILED_TO_UPDATE_CATEGORY: "Failed to update category",
    MSG_PRODUCT_ADDED_SUCCESSFULLY: "Product added successfully",
    MSG_ERROR_ADDING_PRODUCT: "Error adding product",
    MSG_PRODUCT_NOT_FOUND: "Product not found",
    MSG_PRODUCT_EDIT_SUCCESSFULL: "Product Edit successfull",
    MSG_FAILED_TO_UPDATE_PRODUCT: "Failed to update product",
    MSG_PRODUCT_UPDATED: "Product updated",
};
